spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;
    username: sa
    password:

  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.highlight_sql: true
    hibernate:
      ddl-auto: create-drop

  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret:
    key: EGHGKK2959wkOTntmZTsnbT309299nYTr20djhJODJOnpA==